themes = {
  { "catppuccin/nvim", name = "catppuccin" },
  { "EdenEast/nightfox.nvim" },
  { "https://gitlab.com/bartekjaszczak/luma-nvim" },
  { "diegoulloao/neofusion.nvim" },
  { "bakageddy/alduin.nvim" },
  { "https://gitlab.com/bartekjaszczak/finale-nvim" },
  { "killitar/obscure.nvim" },
  { "samharju/serene.nvim" },
  { "0xstepit/flow.nvim" },
  { "slugbyte/lackluster.nvim" },
  { "uloco/bluloco.nvim" },
  { "ptdewey/darkearth-nvim" },
  -- { "loganswartz/sunburn.nvim" },
  { "samharju/synthweave.nvim" },
  { "svermeulen/text-to-colorscheme.nvim" },
  { "miikanissi/modus-themes.nvim" },
  { "alexmozaidze/palenight.nvim" },
  { "scottmckendry/cyberdream.nvim" },
  { "HoNamDuong/hybrid.nvim" },
  { "https://gitlab.com/sxwpb/halfspace.nvim" },
  { "https://gitlab.com/bartekjaszczak/distinct-nvim" },
  { "oxfist/night-owl.nvim" },
  { "polirritmico/monokai-nightasty.nvim" },
  { "cryptomilk/nightcity.nvim" },
  { "ribru17/bamboo.nvim" },
  { "judaew/ronny.nvim" },
  { "Verf/deepwhite.nvim" },
  { "xero/miasma.nvim" },
  {
    "2nthony/vitesse.nvim",
    dependencies = {
      "tjdevries/colorbuddy.nvim",
    },
  },
  { "zootedb0t/citruszest.nvim" },
  { "sekke276/dark_flat.nvim" },
  -- { "sonjiku/yawnc.nvim" },
  { "dasupradyumna/midnight.nvim" },
  { "maxmx03/fluoromachine.nvim" },
  { "nyngwang/nvimgelion" },
  { "embark-theme/vim" },
  { "Yazeed1s/oh-lucy.nvim" },
  { "gbprod/nord.nvim" },
  { "mellow-theme/mellow.nvim" },
  { "olivercederborg/poimandres.nvim" },
  { "Mofiqul/adwaita.nvim" },
  { "lewpoly/sherbet.nvim" },
  { "Yazeed1s/minimal.nvim" },
  { "ramojus/mellifluous.nvim" },
  { "rockyzhang24/arctic.nvim" },
  { "qaptoR-nvim/chocolatier.nvim" },
  { "lmburns/kimbox" },
  { "chrsm/paramount-ng.nvim" },
  { "kvrohit/rasmus.nvim" },
  { "phha/zenburn.nvim" },
  { "cpea2506/one_monokai.nvim" },
  { "tiagovla/tokyodark.nvim" },
  { "kevinm6/kurayami.nvim" },
  { "sho-87/kanagawa-paper.nvim" },
  { "rebelot/kanagawa.nvim" },
  { "titanzero/zephyrium" },
  { "luisiacc/gruvbox-baby" },
  { "echasnovski/mini.nvim", version = "*" },
  { "rktjmp/lush.nvim" },
  { "RishabhRD/gruvy" },
  { "rmehri01/onenord.nvim" },
  { "olimorris/onedarkpro.nvim" },
  { "adisen99/apprentice.nvim" },
  { "Everblush/nvim", name = "everblush" },
  { "ldelossa/vimdark" },
  { "kvrohit/substrata.nvim" },
  { "EdenEast/nightfox.nvim" },
  { "frenzyexists/aquarium-vim" },
  { "zenbones-theme/zenbones.nvim" },
  { "rose-pine/neovim", name = "rose-pine" },
  { "kdheepak/monochrome.nvim" },
  { "projekt0n/github-nvim-theme" },
  { "adisen99/codeschool.nvim" },
  { "nxvu699134/vn-night.nvim" },
  { "yashguptaz/calvera-dark.nvim" },
  { "Mofiqul/dracula.nvim" },
  { "dracula/vim" },
  { "NTBBloodbath/doom-one.nvim" },
  { "neanias/everforest-nvim" },
  { "sainnhe/everforest" },
  { "sainnhe/gruvbox-material" },
  { "navarasu/onedark.nvim" },
  -- {
  --   url = "https://codeberg.org/jthvai/lavender.nvim",
  --   branch = "stable", -- versioned tags + docs updates from main
  --   lazy = false,
  -- },
  { "ishan9299/nvim-solarized-lua" },
  -- { "svrana/neosolarized.nvim" },
  { "Tsuzat/NeoSolarized.nvim" },
  { "shaunsingh/nord.nvim" },
  { "AlexvZyl/nordic.nvim" },
  { "andersevenrud/nordic.nvim" },
  { "fenetikm/falcon" },
  { "savq/melange-nvim" },
  { "ofirgall/ofirkai.nvim", branch = "exp" },
  { "tanvirtin/monokai.nvim" },
  { "ray-x/starry.nvim" },
  { "ray-x/aurora" },
  { "yonlu/omni.vim" },
  { "Th3Whit3Wolf/space-nvim" },
  { "PHSix/nvim-hybrid" },
  { "Th3Whit3Wolf/one-nvim" },
  { "tjdevries/colorbuddy.vim" },
  { "bkegley/gloombuddy" },
  { "theniceboy/nvim-deus" },
  { "sainnhe/edge" },
  { "ishan9299/modus-theme-vim" },
  { "Th3Whit3Wolf/onebuddy" },
  { "jim-at-jibba/ariake.nvim" },
  { "rockerBOO/boo-colorscheme-nvim" },
  { "glepnir/zephyr-nvim" },
  { "nvim-treesitter/nvim-treesitter" },
  -- { "mhartington/oceanic-next" },
  { "kyazdani42/blue-moon" },
  { "nyoom-engineering/oxocarbon.nvim" },
  { "sainnhe/sonokai" },
  { "comfysage/evergarden" },
  { "christianchiarulli/nvcode-color-schemes.vim" },
  { "bluz71/vim-moonfly-colors" },
  { "bluz71/vim-nightfly-colors" },
  { "marko-cerovac/material.nvim" },
  { "askfiy/visual_studio_code" },
  { "Mofiqul/vscode.nvim" },
  { "tomasiser/vim-code-dark" },
  { "rafamadriz/neon" },
  { "Abstract-IDE/Abstract-cs" },
  { "sontungexpt/witch" },
}

return { { "catppuccin/nvim", name = "catppuccin" }, { "EdenEast/nightfox.nvim" } }
